//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisWenAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus
    {
        public bus()
        {
            this.chofer = new HashSet<chofer>();
            this.hace = new HashSet<hace>();
        }
    
        public int Id { get; set; }
        public int Empresa_Id { get; set; }
        public string Patente { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual ICollection<chofer> chofer { get; set; }
        public virtual ICollection<hace> hace { get; set; }
    }
}
