//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisWenAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public empresa()
        {
            this.bus = new HashSet<bus>();
            this.chofer = new HashSet<chofer>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Dirección { get; set; }
        public string Telefono { get; set; }
    
        public virtual ICollection<bus> bus { get; set; }
        public virtual ICollection<chofer> chofer { get; set; }
    }
}
