//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisWenAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class hace
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_termino { get; set; }
        public int Bus_Id { get; set; }
        public int Recorrido_Id { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual recorrido recorrido { get; set; }
    }
}
