//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisWenAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipopasaje
    {
        public tipopasaje()
        {
            this.tipopasaje_recorrido = new HashSet<tipopasaje_recorrido>();
        }
    
        public int Id { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<tipopasaje_recorrido> tipopasaje_recorrido { get; set; }
    }
}
